#! /bin/bash
#PBS -q short
#PBS -N Job-two_p_orbitals_1.com
#PBS -j oe
#PBS -o two_p_orbitals_1.com.qlog
#PBS -l mem=12G
#PBS -l walltime=24:00:00
#PBS -l ncpus=8
#
# Set up the Gaussian environment and prevent core files.
module load g16reva03_lcpu
ulimit -c 0
#
# Set the Gaussian scratch directory to the job-specific SCRATCH directory.
export MY_SCRATCH=`mktemp -u -p "/tmp"`
mkdir $MY_SCRATCH
export GAUSS_SCRDIR="$MY_SCRATCH"
#
# Move to the submission script directory.
cd $PBS_O_WORKDIR
#
# Run Gaussian...
crc_node_print -d > two_p_orbitals_1.log && g16 -m=12GB -p=8 < two_p_orbitals_1.com >> two_p_orbitals_1.log && sed -i 's/Dipole orientation:/Dipole oientation:/' two_p_orbitals_1.log
#
# Remove scratch directory.
rm -rf $MY_SCRATCH
